### PR TITLE
Fixes #19 - path option arguments don't work correctly

### LINKED ISSUE #19: path option arguments don't work correctly
It looks like there is an issue in the interpolate method. For example, this path setting won't be replaced correctly: 
path: 'blog/page:num_en.html'

After performing the interpolate method, it will return blog/pageundefined.html

### PR DESCRIPTION
**Pull request by chebum**
This commit fixes the interpolate method. I also fixes 'lint' warnings that were present in the project and added .editorconfig file to preserve formatting for other contributors.

### CODE REVIEW

**Comment by blakeembrey** [comment]
I won't be accepting the subjective style changes. I also don't think this is a good change as no one can understand that `:numen` is actually `:num` and `en`. It'd be better to just switch to a different template style.

**Comment by blakeembrey** [comment]
How about using https://www.npmjs.com/package/string-template?

**Comment by chebum** [comment]
@blakeembrey Thank you for reviewing the PR. Did I understand correctly that you suggest to introduce a breaking change? Use if string-template library will break a lot of websites after next `npm install`.

**Comment by blakeembrey** [comment]
I'll be bumping the module a major version and updating the docs.

**Comment by chebum** [comment]
Sounds good. I'll prepare a new PR then.

**Pull request closed without merging**
