### PR TITLE
Allow omitting template and layout if pageContents is set

### LINKED ISSUE #39: Does not allow omission of template and layout options
I've just implemented pagination with this plugin (see here: https://github.com/ismay/ismaywolff.nl/commit/df879d291f27f198fa2bb757a79fe5c587c8b779), and it works really well. Only one thing that it does is a minor inconvenience: it requires me to pass a `layout` or `template` option, when in fact I'm using the `pageContents` option with in-place (so I don't need layouts or templates).

I've now set `layout` to a nonsense string (`"none"`) to silence the error (see here: https://github.com/ismay/ismaywolff.nl/blob/master/metalsmith.js#L82), but it would be nice if it was allowed to omit both `layout` and `template` when `pageContents` has been set.

### PR DESCRIPTION
**Pull request by ghost**
Closes #39

### CODE REVIEW

**Comment by ghost** [comment]
Any news on this? Would you be open to merging this? The build has stalled btw, might just need a reset to pass.

**Comment by ghost** [comment]
Bump

**Comment by blakeembrey** [comment]
@ismay I'm sorry, I did not see this originally. LGTM 👍

**Comment by ghost** [comment]
👍 No problem, thanks for merging!

**Pull request merged**
