### PR TITLE
Add the ability to filter which items in a collection should be paginate...

### PR DESCRIPTION
**Pull request by boushley**
...d.

This allows for dividing a collection up without needing to create extra collections.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@boushley You'll need to remove the extra semicolons and add a test case to make sure this works. However, functions can't be specified in JSON. I'd suggest allowing strings and using a module like `to-function`.

**Comment by boushley** [comment]
@blakeembrey Alright, added support for object or string filtering using `to-function` and added tests.

Also updated the other tests to avoid shared state between tests via the `files` object.

**Comment by blakeembrey** [comment]
Thanks :+1:

**Comment by blakeembrey** [comment]
Released with `v1.1.0`

**Pull request merged**
